### ISSUE TITLE
Hi, How can I use it?

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#1]

**Comment by whistyun** [comment]
First at all, this project is not packaged and not upload to nuget yet.
So you should include "Markdown.Avalonia" and "ColorTextBlock.Avalonia" to your project.

You can use MarkdownScrollViewer to render markdown.
Now I'm making a simple sample. 
If you allow to read complicated example, see [Markdown.AvaloniaDemo](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.AvaloniaDemo/Views/MainWindow.axaml).

**Comment by dayAndnight2018** [comment]
> First at all, this project is not packaged and not upload to nuget yet.
> So you should include "Markdown.Avalonia" and "ColorTextBlock.Avalonia" to your project.
> 
> You can use MarkdownScrollViewer to render markdown.
> Now I'm making a simple sample.
> If you allow to read complicated example, see [Markdown.AvaloniaDemo](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.AvaloniaDemo/Views/MainWindow.axaml).

it is crazy! So hope for your nuget! Please!

**Comment by whistyun** [comment]
I created nupkg and upload to nuget.org.
Because it is currently under review, please wait for a while.

https://www.nuget.org/packages/Markdown.Avalonia/

**Comment by dayAndnight2018** [comment]
> I created nupkg and upload to nuget.org.
> Because it is currently under review, please wait for a while.
> 
> https://www.nuget.org/packages/Markdown.Avalonia/

I tried serval minutes ago, only to find it is not support Chinese! What a pity! Could you fix this problem trying expose the FontFamily of the MarkdownScrollViewer ?

**Comment by dayAndnight2018** [comment]
> I created nupkg and upload to nuget.org.
> Because it is currently under review, please wait for a while.
> 
> https://www.nuget.org/packages/Markdown.Avalonia/

besides, could you please expose more interfaces to offer chances we can custom the different style for different tag, for example we could custom the size of "##" or custom the color of "###" references the markdown control given by https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit!

**Comment by whistyun** [comment]
Unfortunately, the current version requires you to set FontFamily for each item.
Also you can also change the color etc. by using Selector in MarkdownScrollViewer.Styles.
I will prepare a document about the class name.

**sample**
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia"
             xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="CustomStyle.SetStyles">

  <md:MarkdownScrollViewer>
    <md:MarkdownScrollViewer.Styles>
      <!-- for viewing Chinese, change familly name. -->
      <Style Selector="ctxt|CTextBlock">
        <Setter Property="FontFamily" Value="Noto Sans SC"/>
      </Style>
      <Style Selector="TextBlock">
        <Setter Property="FontFamily" Value="Noto Sans SC"/>
      </Style>

      <!-- change heading1 style -->
      <Style Selector="ctxt|CTextBlock.Heading1">
        <Setter Property="Foreground" Value="AliceBlue"/>
        <Setter Property="Background" Value="DarkBlue"/>
      </Style>

      <Style Selector=".Blockquote ctxt|CTextBlock.Heading1">
        <Setter Property="FontSize" Value="13"/>
      </Style>
    </md:MarkdownScrollViewer.Styles>

    # 他们所有的设备

    ## Heading2

    他们所有的设备和仪器彷佛都是有生命的
    
    * 他们所有的设备和仪器彷佛都是有生命的。
    * listitem2

    | col1 | col2 | col3 |
    |------|------|------|
    | one  |------|------|
    | two  |------|------|

    > #blockquote
    >
    > p>. and enhance syntax
  </md:MarkdownScrollViewer>
</UserControl>
```
![screenshot](https://user-images.githubusercontent.com/13712028/101062220-b8851380-35d4-11eb-9b14-9e4335277767.png)

**Comment by dayAndnight2018** [comment]
> Unfortunately, the current version requires you to set FontFamily for each item.
> Also you can also change the color etc. by using Selector in MarkdownScrollViewer.Styles.
> I will prepare a document about the class name.
> 
> **sample**
> 
> ```
> <UserControl xmlns="https://github.com/avaloniaui"
>              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>              xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>              xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>              xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia"
>              xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia"
>              mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
>              x:Class="CustomStyle.SetStyles">
> 
>   <md:MarkdownScrollViewer>
>     <md:MarkdownScrollViewer.Styles>
>       
>       <Style Selector="ctxt|CTextBlock">
>         <Setter Property="FontFamily" Value="Noto Sans SC"/>
>       </Style>
>       <Style Selector="TextBlock">
>         <Setter Property="FontFamily" Value="Noto Sans SC"/>
>       </Style>
> 
>       
>       <Style Selector="ctxt|CTextBlock.Heading1">
>         <Setter Property="Foreground" Value="AliceBlue"/>
>         <Setter Property="Background" Value="DarkBlue"/>
>       </Style>
> 
>       <Style Selector=".Blockquote ctxt|CTextBlock.Heading1">
>         <Setter Property="FontSize" Value="13"/>
>       </Style>
>     </md:MarkdownScrollViewer.Styles>
> 
>     # 他们所有的设备
> 
>     ## Heading2
> 
>     他们所有的设备和仪器彷佛都是有生命的
>     
>     * 他们所有的设备和仪器彷佛都是有生命的。
>     * listitem2
> 
>     | col1 | col2 | col3 |
>     |------|------|------|
>     | one  |------|------|
>     | two  |------|------|
> 
>     > #blockquote
>     >
>     > p>. and enhance syntax
>   </md:MarkdownScrollViewer>
> </UserControl>
> ```
> 
> ![screenshot](https://user-images.githubusercontent.com/13712028/101062220-b8851380-35d4-11eb-9b14-9e4335277767.png)

Thanks a lot! It works now!
By the way, is there no heading5 and heading 6?
![image](https://user-images.githubusercontent.com/44399091/101105770-64e0ed00-3609-11eb-85e9-c8911416112b.png)
![image](https://user-images.githubusercontent.com/44399091/101105806-7a561700-3609-11eb-8969-ca56ff7c4fba.png)

**Comment by dayAndnight2018** [comment]
> > Unfortunately, the current version requires you to set FontFamily for each item.
> > Also you can also change the color etc. by using Selector in MarkdownScrollViewer.Styles.
> > I will prepare a document about the class name.
> > **sample**
> > ```
> > <UserControl xmlns="https://github.com/avaloniaui"
> >              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
> >              xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
> >              xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
> >              xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia"
> >              xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia"
> >              mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
> >              x:Class="CustomStyle.SetStyles">
> > 
> >   <md:MarkdownScrollViewer>
> >     <md:MarkdownScrollViewer.Styles>
> >       
> >       <Style Selector="ctxt|CTextBlock">
> >         <Setter Property="FontFamily" Value="Noto Sans SC"/>
> >       </Style>
> >       <Style Selector="TextBlock">
> >         <Setter Property="FontFamily" Value="Noto Sans SC"/>
> >       </Style>
> > 
> >       
> >       <Style Selector="ctxt|CTextBlock.Heading1">
> >         <Setter Property="Foreground" Value="AliceBlue"/>
> >         <Setter Property="Background" Value="DarkBlue"/>
> >       </Style>
> > 
> >       <Style Selector=".Blockquote ctxt|CTextBlock.Heading1">
> >         <Setter Property="FontSize" Value="13"/>
> >       </Style>
> >     </md:MarkdownScrollViewer.Styles>
> > 
> >     # 他们所有的设备
> > 
> >     ## Heading2
> > 
> >     他们所有的设备和仪器彷佛都是有生命的
> >     
> >     * 他们所有的设备和仪器彷佛都是有生命的。
> >     * listitem2
> > 
> >     | col1 | col2 | col3 |
> >     |------|------|------|
> >     | one  |------|------|
> >     | two  |------|------|
> > 
> >     > #blockquote
> >     >
> >     > p>. and enhance syntax
> >   </md:MarkdownScrollViewer>
> > </UserControl>
> > ```
> > 
> > 
> > ![screenshot](https://user-images.githubusercontent.com/13712028/101062220-b8851380-35d4-11eb-9b14-9e4335277767.png)
> 
> Thanks a lot! It works now!
> By the way, is there no heading5 and heading 6?
> ![image](https://user-images.githubusercontent.com/44399091/101105770-64e0ed00-3609-11eb-85e9-c8911416112b.png)
> ![image](https://user-images.githubusercontent.com/44399091/101105806-7a561700-3609-11eb-8969-ca56ff7c4fba.png)

I think I know the reason. Hope you support more tag for example imgage, link, etc.
