### ISSUE TITLE
Missing version on Nuget source

### ISSUE THREAD

**Issue by laolarou726** [whistyun/Markdown.Avalonia#100]
Version `11.0.0-a10` is missing on the Nuget source. Do I need to add a custom package source in order to install the latest version?

**Comment by laolarou726** [comment]
I just noticed 11.0.0-a10 is in the middle of the versions list. VS versioning may have some bug

**Comment by IhateTrains** [comment]
`11.0.0-a10` doesn't display for me, I think it's missing from NuGet:
![obraz](https://user-images.githubusercontent.com/29546927/227718082-08e27e28-1e79-48b8-9a83-0d49ebe5c4fb.png)

**Comment by whistyun** [comment]
Did you search Markdown.Avalonia instead of Markdown.Avalonia.Tight?
For now, I hove not release Markdown.Avalonia and Markdown.Avalonia.SyntaxHigh to wait for AvaloniaEdit released.

**Comment by IhateTrains** [comment]
What I uploaded above is the version list of Markdown.Avalonia, but Markdown.Avalonia.Tight also doesn't have the a10 version: 
![Screenshot_20230325-165912.png](https://user-images.githubusercontent.com/29546927/227728345-3a960865-e77b-4648-b7f4-a2ec58da1f6a.png)

**Comment by laolarou726** [comment]
> What I uploaded above is the version list of Markdown.Avalonia, but Markdown.Avalonia.Tight also doesn't have the a10 version: 
> ![Screenshot_20230325-165912.png](https://user-images.githubusercontent.com/29546927/227728345-3a960865-e77b-4648-b7f4-a2ec58da1f6a.png)
> 
> 

It's in the middle of the list, can you scroll down a little bit?

**Comment by IhateTrains** [comment]
> > What I uploaded above is the version list of Markdown.Avalonia, but Markdown.Avalonia.Tight also doesn't have the a10 version:
> 
> It's in the middle of the list, can you scroll down a little bit?

Indeed, @whistyun sorry for confusion.

**Comment by whistyun** [comment]
Thanks for all your help.
"a10" is hard to see on the list. So I will change version to "b1".
