### ISSUE TITLE
Table looks not good

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#101]
just like the following picture, I want them auto fit in width, not dividend equally.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/44399091/227761314-f1f838f9-9a76-4b2b-ac25-9d7204b9bf0d.png">

**Comment by whistyun** [comment]
Markdown.Avalonia 0.10.14 has be released.
It adjusts table column width based on content width.
![image](https://user-images.githubusercontent.com/13712028/230735579-530d7338-fa67-419b-9861-d63fb74478e2.png)

**Comment by dayAndnight2018** [comment]
well done, thanks!
