### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by cezarypiatek** [whistyun/Markdown.Avalonia#121]
After upgrading from `11.0.0-b1` to `11.0.0`  syntax highlighting stopped working. Tested on `cs` and `json` languages.

Branch with updated package for affected app https://github.com/WireMock-Net/WireMockInspector/tree/feature/migrate_avalonia

![image](https://github.com/whistyun/Markdown.Avalonia/assets/7759991/5cd5a35f-4ca2-426e-bd4d-28c87f0007b2)

![image](https://github.com/whistyun/Markdown.Avalonia/assets/7759991/c51e7252-9b06-4d5d-941b-606b80745e8f)

**Comment by whistyun** [comment]
Markdown.Avalonia 11.0.1 has be released.
This version fixes the issue.

**Comment by cezarypiatek** [comment]
Thanks for a help. It's working correctly now.
