### ISSUE TITLE
Native AOT Crashes on Startup

### ISSUE THREAD

**Issue by cybertron-cube** [whistyun/Markdown.Avalonia#122]
Using 11.0.0 release and building with PublishAot set to true, the text ```: https://github.com``` in MarkDownScrollViewer causes the application to crash. It seems any colon followed by a web link causes this crash when compiling with AOT.

Starting a new Avalonia project and putting this
![image](https://github.com/whistyun/Markdown.Avalonia/assets/54194687/2761ab9b-bb0d-48de-ba07-67770f0c84ab)
in MainWindow.axaml along with setting PublishAot to true is what I did to produce the exception below

<details>
<summary>Exception Details</summary>
<br>
System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
<br> ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
<br>   at System.Reflection.Assembly.GetCallingAssembly() + 0x5b
<br>   at Markdown.Avalonia.EmojiTable.LoadTxt() + 0x5c
<br>   at Markdown.Avalonia.EmojiTable..cctor() + 0x1e
<br>   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xc6
<br>   --- End of inner exception stack trace ---
<br>   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x167
<br>   at <br>System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0xd
<br>   at Markdown.Avalonia.EmojiTable.TryGet(String, String&) + 0x19
<br>   at Markdown.Avalonia.Markdown.DoTextDecorations(String, Func`2) + 0x1e4
<br>   at Markdown.Avalonia.Markdown.<PrivateRunSpanGamut>g__RunSpanRest|74_0(String, Int32, Int32, Int32, List`1) + 0x159
<br>   at Markdown.Avalonia.Markdown.PrivateRunSpanGamut(String) + 0x4d
<br>   at Markdown.Avalonia.Markdown.<FormParagraphs>d__78.MoveNext() + 0x1a4
<br>   at System.Collections.Generic.List`1.InsertRange(Int32, IEnumerable`1) + 0x120
<br>   at Markdown.Avalonia.Markdown.<PrivateRunBlockGamut>g__RunBlockRest|73_0(String, Int32, Int32, ParseStatus, Int32, List`1) + 0x154
<br>   at Markdown.Avalonia.Markdown.PrivateRunBlockGamut(String, ParseStatus) + 0x308
<br>   at Markdown.Avalonia.Markdown.Transform(String) + 0x3c
<br>   at Markdown.Avalonia.MarkdownScrollViewer.UpdateMarkdown() + 0x3b
<br>   at MpvTest.Views.MainWindow.!XamlIlPopulate(IServiceProvider, MainWindow) + 0x22e
<br>   at MpvTest.Views.MainWindow.InitializeComponent(Boolean) + 0x14
<br>   at MpvTest.App.OnFrameworkInitializationCompleted() + 0x41
<br>   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode) + 0x4b
<br>   at MpvTest.Program.Main(String[]) + 0x21
</details>

**Comment by whistyun** [comment]
Markdown.Avalonia 11.0.1 has be released.
This version fixes the issue.

**Comment by cybertron-cube** [comment]
Thank you and great work!
