### ISSUE TITLE
0.10 RC update ?

### ISSUE THREAD

**Issue by fforjan** [whistyun/Markdown.Avalonia#14]
As the new RC is bringing assemblies with strong name, packages need to be generated against those 'new' references.

**Comment by whistyun** [comment]
Thanks.
I spent time on search a way to work with both preview6 and rc1 ( (and preview1-5).
I was able to avoid wasting this time.

[0.10.0-a5](https://www.nuget.org/packages/Markdown.Avalonia/0.10.0-a5) work with RC1
