### ISSUE TITLE
update image behavior ?

### ISSUE THREAD

**Issue by fforjan** [whistyun/Markdown.Avalonia#20]
i'm trying to render some markdown document which contains image, but this is behaving weirdly.
As example, when rendering https://github.com/AvaloniaUI/Avalonia/wiki/Projects-that-are-using-Avalonia
The images are not fitting the current window with and it seems weird from user point of view :

![image](https://user-images.githubusercontent.com/601810/102499551-2f3bfb00-4030-11eb-9a6d-bfaa7820fc70.png)

**Comment by whistyun** [comment]
thanks to report it.
I will modify to adjust the size to fit control width. 

![image](https://user-images.githubusercontent.com/13712028/102508713-129fd180-40c9-11eb-9e67-2283223816a9.png)

**Comment by whistyun** [comment]
![image](https://user-images.githubusercontent.com/13712028/102511099-ba1e0380-40cb-11eb-81b2-cecf4046793c.png)

**Comment by fforjan** [comment]
you're fast !!!

**Comment by whistyun** [comment]
This modify is included in 0.9.0-a7 and 0.10.0-a7.

**Comment by fforjan** [comment]
awesome ! works like a charm !
