### ISSUE TITLE
It is a bug

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#25]
When I input an English sentence, it looks like this:

![image](https://user-images.githubusercontent.com/44399091/102960641-522d4a00-451d-11eb-8ee3-d7e69384f044.png)

I think it is a bug to translate "I" to the order symbol "i."

**Comment by whistyun** [comment]
thanks for report.

To fix this issue, I have to make the rule of list markers strict.

In particular

1. roman number order must start with 'i,' ～ 'iii,'. and disallow other character than [cdilmvx].
2. alphabet order must start with 'a,' ～ 'c,'. and, in grammatically, list markers with two or more characters are disallowd (display is allowed).

![image](https://user-images.githubusercontent.com/13712028/103044015-46479380-45c2-11eb-952b-022cca97f41d.png)

**Comment by whistyun** [comment]
I will reclose after release

**Comment by dayAndnight2018** [comment]
> I will reclose after release

ok

**Comment by whistyun** [comment]
this feature released in 0.10.0-a8 and 0.9.0-a8.
