### ISSUE TITLE
How can I fix it?

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#27]
When I use `Chinese word`， there must be something wrong:

![image](https://user-images.githubusercontent.com/44399091/103136909-5b760c80-46ff-11eb-9216-2a15c66d4806.png)

**Comment by whistyun** [comment]
I expose 'MonospaceFontFamily' in 0.10.0-a8 and 0.9.0-a8.

For now, it is necessary to set for CCode, but Iwill consider whether it is possible to add a new property to MarkdownScrollViewer, including FontFamily.
```
<Style Selector="ctxt|CCode">
    <Setter Property="MonospaceFontFamily" Value="Noto Sans SC"/>
</Style>
```

Please note that this version change style automaly to fit used theme(#19).
The style chosen by this feature is subtly different from the previous ones.
If you like the old ones, change the Markdown Scroll Viewer settings.

```xml
<md:MarkdownScrollViewer
                 MarkdownStyleName="Standard" 
                 />
```

**Comment by dayAndnight2018** [comment]
> I expose 'MonospaceFontFamily' in 0.10.0-a8 and 0.9.0-a8.
> 
> For now, it is necessary to set for CCode, but Iwill consider whether it is possible to add a new property to MarkdownScrollViewer, including FontFamily.
> 
> ```
> <Style Selector="ctxt|CCode">
>     <Setter Property="MonospaceFontFamily" Value="Noto Sans SC"/>
> </Style>
> ```
> 
> Please note that this version change style automaly to fit used theme(#19).
> The style chosen by this feature is subtly different from the previous ones.
> If you like the old ones, change the Markdown Scroll Viewer settings.
> 
> ```
> <md:MarkdownScrollViewer
>                  MarkdownStyleName="Standard" 
>                  />
> ```

it works, thanks!
