### ISSUE TITLE
There must be something wrong

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#29]
![image](https://user-images.githubusercontent.com/44399091/103290073-a6f02980-4a23-11eb-87bf-076439264cc6.png)
Like what in the picture, the use of number and "i.ii.iii." are in a wrong order. The location of the number is also wrong.

**Comment by whistyun** [comment]
Roman order list syntax is not period(.) but comma(,).
And If you want to make roman list as sublist of number list, you should indent.

```
1. one-one
    i, one
    ii, two
    iii, three
2. two-one
3. three-one
```
![image](https://user-images.githubusercontent.com/13712028/103291850-02281900-4a30-11eb-8bc6-f8cf523cd460.png)

**Comment by dayAndnight2018** [comment]
> Roman order list syntax is not period(.) but comma(,).
> And If you want to make roman list as sublist of number list, you should indent.
> 
> ```
> 1. one-one
>     i, one
>     ii, two
>     iii, three
> 2. two-one
> 3. three-one
> ```
> 
> ![image](https://user-images.githubusercontent.com/13712028/103291850-02281900-4a30-11eb-8bc6-f8cf523cd460.png)

got it
