### ISSUE TITLE
Maybe there needs a contrast table to show how to custom the style

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#4]
Maybe there needs a contrast table to show how to custom the style, for example, offer lines of code and an image of the real effect. In this way, users may have a direct feeling about how to custom the style of the control.

```
---------------------------------------------------------------------
<style>                    |
····                       |     an image to show effect
</style>                   |

---------------------------------------------------------------------

```

**Comment by whistyun** [comment]
Is this a suggestion on how to create a document?
Certainly, I need to specify how to style elements, and show the effect.

I want to copy code in the sample and since I don't know how to set code in table-cell, so I write the sentence by chapter in the wiki.
... [but not yet completed](https://github.com/whistyun/Markdown.Avalonia/wiki/How-to-cunstomise-style).

**Comment by dayAndnight2018** [comment]
Sure, I write the same code  to change the style only to find no effect. So i think we need a effect image shown clearly.

**Comment by dayAndnight2018** [comment]
> Is this a suggestion on how to create a document?
> Certainly, I need to specify how to style elements, and show the effect.
> 
> I want to copy code in the sample and since I don't know how to write code in table-cell, so I write the sentence by chapter in wiki.
> ... [but not yet completed](https://github.com/whistyun/Markdown.Avalonia/wiki/How-to-customise-style).

maybe, the text of hyperlink could be bold when mouse is hovering.

**Comment by dayAndnight2018** [comment]
> Is this a suggestion on how to create a document?
> Certainly, I need to specify how to style elements, and show the effect.
> 
> I want to copy code in the sample and since I don't know how to write code in table-cell, so I write the sentence by chapter in wiki.
> ... [but not yet completed](https://github.com/whistyun/Markdown.Avalonia/wiki/How-to-customise-style).

![image](https://user-images.githubusercontent.com/44399091/101270047-00ac5d80-37b0-11eb-8e6e-06c0a6560e2e.png)

1. I can not see the effect of italic.
2. How can I set the Foreground of the odd/even table row?
3. There must be something wrong when I use * list1 * list2 after 1. list1 2.list2
4. The Padding Property has no effect on block quote text like what in the image.
5. I want to set the border corner radius and padding of the Ccode, but not know how to.
6. If it can be exposed the hyperlink mouse hover and leave after clicked effect could be more appreciate.

**Comment by whistyun** [comment]
(about 1) Can you tell me your using font? I can't reproduce it.  
(about 2 and 4)  Can you tell me your style-settings?
(about 3)  Sorry, I try to repair it.

**Comment by dayAndnight2018** [comment]
> (about 1) Can you tell me your using font? I can't reproduce it.
> (about 2 and 4) Can you tell me your style-settings?
> (about 3) Sorry, I try to repair it.

1. FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简"
2 & 4 are how to do questions.

**Comment by dayAndnight2018** [comment]
> (about 1) Can you tell me your using font? I can't reproduce it.
> (about 2 and 4) Can you tell me your style-settings?
> (about 3) Sorry, I try to repair it.

About No2, I solved it.

![image](https://user-images.githubusercontent.com/44399091/101273363-9b686480-37cf-11eb-94ff-81cca81f64b9.png)

**Comment by whistyun** [comment]
**About No2 (Just in case...)**  
Table-cell which is Border have class either TableHeader, OddTableRow or EvenTableRow.
So you have to use [child/descendant selector](https://avaloniaui.net/docs/styles/selectors)

## Sample ##
```xml
<Style Selector=".TableHeader ctxt|CTextBlock">
    <Setter Property="Foreground" Value="Red"/>
</Style>
<Style Selector=".OddTableRow ctxt|CTextBlock">
    <Setter Property="Foreground" Value="Blue"/>
</Style>
<Style Selector=".EvenTableRow ctxt|CTextBlock">
    <Setter Property="Foreground" Value="Green"/>
</Style>
```
![sample table ivew](https://user-images.githubusercontent.com/13712028/101274034-16387c00-37de-11eb-9b32-70fc92f19dfe.png)

**Comment by dayAndnight2018** [comment]
> **About No2 (Just in case...)**
> Table-cell which is Border have class either TableHeader, OddTableRow or EvenTableRow.
> So you have to use [child/descendant selector](https://avaloniaui.net/docs/styles/selectors)
> 
> ## Sample
> ```
> <Style Selector=".TableHeader ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Red"/>
> </Style>
> <Style Selector=".OddTableRow ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Blue"/>
> </Style>
> <Style Selector=".EvenTableRow ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Green"/>
> </Style>
> ```
> 
> ![sample table ivew](https://user-images.githubusercontent.com/13712028/101274034-16387c00-37de-11eb-9b32-70fc92f19dfe.png)

What about changing single line or two lines color? I mean "---", "___", "***" and "===";

**Comment by dayAndnight2018** [comment]
> **About No2 (Just in case...)**
> Table-cell which is Border have class either TableHeader, OddTableRow or EvenTableRow.
> So you have to use [child/descendant selector](https://avaloniaui.net/docs/styles/selectors)
> 
> ## Sample
> ```
> <Style Selector=".TableHeader ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Red"/>
> </Style>
> <Style Selector=".OddTableRow ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Blue"/>
> </Style>
> <Style Selector=".EvenTableRow ctxt|CTextBlock">
>     <Setter Property="Foreground" Value="Green"/>
> </Style>
> ```
> 
> ![sample table ivew](https://user-images.githubusercontent.com/13712028/101274034-16387c00-37de-11eb-9b32-70fc92f19dfe.png)

The effect of my markdownEditor is now:

https://github.com/dayAndnight2018/MarkDownAvalonia/blob/master/introduction.md

Thanks for your help!

Maybe I need more help from you!

**Comment by whistyun** [comment]
**About No4**
Blockquote is created by using Border.
In my environment Padding property is effectable.
```xml
<Style Selector="Border.Blockquote">
    <Setter Property="BorderBrush" Value="Red" />
    <Setter Property="Background" Value="Pink" />
    <Setter Property="BorderThickness" Value="4,12,8,16"/>
    <Setter Property="Padding" Value="20,20,0,0"/>
</Style>
```
![sample blockquote](https://user-images.githubusercontent.com/13712028/101274167-2b61da80-37df-11eb-91d3-124d5c0449a8.png)

I'm afraid my document misleads you and causes to make the wrong selector.

**Comment by dayAndnight2018** [comment]
> **About No4**
> Blockquote is created by using Border.
> In my environment Padding property is effectable.
> 
> ```
> <Style Selector="Border.Blockquote">
>     <Setter Property="BorderBrush" Value="Red" />
>     <Setter Property="Background" Value="Pink" />
>     <Setter Property="BorderThickness" Value="4,12,8,16"/>
>     <Setter Property="Padding" Value="20,20,0,0"/>
> </Style>
> ```
> 
> ![sample blockquote](https://user-images.githubusercontent.com/13712028/101274167-2b61da80-37df-11eb-91d3-124d5c0449a8.png)
> 
> I'm afraid my document misleads you and causes to make the wrong selector.

I shall list  all style here:

`
<Style Selector="TextBlock">
                                                            <Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock">
                                                            <Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"></Setter>
                                                            <Setter Property="Foreground" Value="white"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading1">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="28"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading2">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="24"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading3">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="20"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading4">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="16"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading5">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="12"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    <Style Selector="ctxt|CTextBlock.Heading6">
                                                            <Setter Property="Foreground" Value="#C75049"></Setter>
                                                            <Setter Property="FontSize" Value="10"></Setter>
                                                            <Setter Property="FontWeight" Value="Bold"></Setter>
                                                            <Setter Property="Background" Value="TransParent"></Setter>
                                                    </Style>
                                                    
                                                    <Style Selector="Border.Blockquote">
                                                            <Style.Setters>
                                                                    <Setter Property="BorderBrush"     Value="#DEDEDE"/>
                                                                    <Setter Property="BorderThickness" Value="5,0,0,0"/>
                                                                    <Setter Property="Background" Value="#C75049"></Setter>
                                                            </Style.Setters>
                                                    </Style>

                                                    <Style Selector="StackPanel.Blockquote">
                                                            <Style.Setters>
                                                                    <Setter Property="Margin" Value="10,5"/>
                                                                    <Setter Property="Background" Value="#C75049"></Setter>
                                                            </Style.Setters>
                                                    </Style>
                                                    
                                                    <Style Selector="ctxt|CTextBlock.Note">
                                                            <Setter Property="Background" Value="#C75049"></Setter>
                                                            <Setter Property="Foreground" Value="white"></Setter>
                                                    </Style>
                                                    
                                                    <Style Selector="Border.Table">
                                                            <Style.Setters>
                                                                    <Setter Property="Padding" Value="5"/>
                                                                    <Setter Property="BorderThickness" Value="0.5"/>
                                                                    <Setter Property="BorderBrush" Value="silver"/>
                                                            </Style.Setters>
                                                    </Style>

                                                    <Style Selector="Grid.Table > Border">
                                                            <Style.Setters>
                                                                    <Setter Property="Margin" Value="0"/>
                                                                    <Setter Property="BorderThickness" Value="0.5"/>
                                                                    <Setter Property="BorderBrush" Value="silver"/>
                                                                    <Setter Property="Padding" Value="13, 6"/>
                                                            </Style.Setters>
                                                    </Style>

                                                    
                                                    <Style Selector="Border.TableHeader">
                                                            <Style.Setters>
                                                                    <Setter Property="Background" Value="#C75049"/>
                                                            </Style.Setters>
                                                    </Style>
                                                    <Style Selector="Border.TableHeader ctxt|CTextBlock">
                                                            <Style.Setters>
                                                                    <Setter Property="FontWeight" Value="Bold"/>
                                                            </Style.Setters>
                                                    </Style>
                                                    
                                                    <Style Selector="Border.OddTableRow">
                                                            <Style.Setters>
                                                                    <Setter Property="Background" Value="white"/>
                                                            </Style.Setters>
                                                    </Style>

                                                    <Style Selector="Border.EvenTableRow">
                                                            <Style.Setters>
                                                                    <Setter Property="Background" Value="lightgray"/>
                                                            </Style.Setters>
                                                    </Style>
                                                    
                                                    <Style Selector=".OddTableRow ctxt|CTextBlock">
                                                            <Style.Setters>
                                                                    <Setter Property="Foreground" Value="black"/>
                                                            </Style.Setters>
                                                    </Style>

                                                    <Style Selector="Border.EvenTableRow ctxt|CTextBlock">
                                                            <Style.Setters>
                                                                    <Setter Property="Foreground" Value="black"/>
                                                            </Style.Setters>
                                                    </Style>
                                                    
                                                    <Style Selector="Border.CodeBlock">
                                                            <Style.Setters>
                                                                    <Setter Property="BorderThickness" Value="0"/>
                                                                    <Setter Property="Padding" Value="10"></Setter>
                                                                    <Setter Property="Margin"          Value="5,0,5,0"/>
                                                                    <Setter Property="Background"      Value="silver"/>
                                                                    <Setter Property="CornerRadius" Value="2"></Setter>
                                                            </Style.Setters>
                                                    </Style>
                                                    <Style Selector="TextBlock.CodeBlock">
                                                            <Style.Setters>
                                                                    <Setter Property="Foreground"      Value="black"/>
                                                            </Style.Setters>
                                                    </Style>

                                                    <Style Selector="ctxt|CCode">
                                                            <Style.Setters>
                                                                    <Setter Property="Foreground" Value="white" />
                                                                    <Setter Property="Background" Value="#C75049" />
                                                            </Style.Setters>
                                                    </Style>
                                                    
                                                    
                                                    <Style Selector="ctxt|CHyperlink">
                                                            <Style.Setters>
                                                                    <Setter Property="IsUnderline" Value="true"/>
                                                                    <Setter Property="Foreground" Value="#C75049"/>
                                                                    <Setter Property="HoverForeground" Value="#C75049"/>
                                                            </Style.Setters>
                                                    </Style>
`

The single line color or two lines color still black now! How to change it?

**Comment by whistyun** [comment]
** About line**  
Single line's color and Two line's color is not exposed.
I will expose these property in next version.

**Comment by dayAndnight2018** [comment]
> > **About No4**
> > Blockquote is created by using Border.
> > In my environment Padding property is effectable.
> > ```
> > <Style Selector="Border.Blockquote">
> >     <Setter Property="BorderBrush" Value="Red" />
> >     <Setter Property="Background" Value="Pink" />
> >     <Setter Property="BorderThickness" Value="4,12,8,16"/>
> >     <Setter Property="Padding" Value="20,20,0,0"/>
> > </Style>
> > ```
> > 
> > 
> > ![sample blockquote](https://user-images.githubusercontent.com/13712028/101274167-2b61da80-37df-11eb-91d3-124d5c0449a8.png)
> > I'm afraid my document misleads you and causes to make the wrong selector.
> 
> I shall list all style here:
> 
> `
> 
> <Style Selector="TextBlock"> </Style>
> ```
>                                                 <Style Selector="ctxt|CTextBlock">
>                                                         <Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"></Setter>
>                                                         <Setter Property="Foreground" Value="white"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading1">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="28"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading2">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="24"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading3">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="20"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading4">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="16"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading5">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="12"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 <Style Selector="ctxt|CTextBlock.Heading6">
>                                                         <Setter Property="Foreground" Value="#C75049"></Setter>
>                                                         <Setter Property="FontSize" Value="10"></Setter>
>                                                         <Setter Property="FontWeight" Value="Bold"></Setter>
>                                                         <Setter Property="Background" Value="TransParent"></Setter>
>                                                 </Style>
>                                                 
>                                                 <Style Selector="Border.Blockquote">
>                                                         <Style.Setters>
>                                                                 <Setter Property="BorderBrush"     Value="#DEDEDE"/>
>                                                                 <Setter Property="BorderThickness" Value="5,0,0,0"/>
>                                                                 <Setter Property="Background" Value="#C75049"></Setter>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 <Style Selector="StackPanel.Blockquote">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Margin" Value="10,5"/>
>                                                                 <Setter Property="Background" Value="#C75049"></Setter>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 
>                                                 <Style Selector="ctxt|CTextBlock.Note">
>                                                         <Setter Property="Background" Value="#C75049"></Setter>
>                                                         <Setter Property="Foreground" Value="white"></Setter>
>                                                 </Style>
>                                                 
>                                                 <Style Selector="Border.Table">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Padding" Value="5"/>
>                                                                 <Setter Property="BorderThickness" Value="0.5"/>
>                                                                 <Setter Property="BorderBrush" Value="silver"/>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 <Style Selector="Grid.Table > Border">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Margin" Value="0"/>
>                                                                 <Setter Property="BorderThickness" Value="0.5"/>
>                                                                 <Setter Property="BorderBrush" Value="silver"/>
>                                                                 <Setter Property="Padding" Value="13, 6"/>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 
>                                                 <Style Selector="Border.TableHeader">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Background" Value="#C75049"/>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 <Style Selector="Border.TableHeader ctxt|CTextBlock">
>                                                         <Style.Setters>
>                                                                 <Setter Property="FontWeight" Value="Bold"/>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 
>                                                 <Style Selector="Border.OddTableRow">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Background" Value="white"/>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 <Style Selector="Border.EvenTableRow">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Background" Value="lightgray"/>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 
>                                                 <Style Selector=".OddTableRow ctxt|CTextBlock">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Foreground" Value="black"/>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 <Style Selector="Border.EvenTableRow ctxt|CTextBlock">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Foreground" Value="black"/>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 
>                                                 <Style Selector="Border.CodeBlock">
>                                                         <Style.Setters>
>                                                                 <Setter Property="BorderThickness" Value="0"/>
>                                                                 <Setter Property="Padding" Value="10"></Setter>
>                                                                 <Setter Property="Margin"          Value="5,0,5,0"/>
>                                                                 <Setter Property="Background"      Value="silver"/>
>                                                                 <Setter Property="CornerRadius" Value="2"></Setter>
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 <Style Selector="TextBlock.CodeBlock">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Foreground"      Value="black"/>
>                                                         </Style.Setters>
>                                                 </Style>
> 
>                                                 <Style Selector="ctxt|CCode">
>                                                         <Style.Setters>
>                                                                 <Setter Property="Foreground" Value="white" />
>                                                                 <Setter Property="Background" Value="#C75049" />
>                                                         </Style.Setters>
>                                                 </Style>
>                                                 
>                                                 
>                                                 <Style Selector="ctxt|CHyperlink">
>                                                         <Style.Setters>
>                                                                 <Setter Property="IsUnderline" Value="true"/>
>                                                                 <Setter Property="Foreground" Value="#C75049"/>
>                                                                 <Setter Property="HoverForeground" Value="#C75049"/>
>                                                         </Style.Setters>
>                                                 </Style>
> ```
> 
> `
> 
> The single line color or two lines color still black now! How to change it?

![image](https://user-images.githubusercontent.com/44399091/101274599-82b17c00-37da-11eb-972e-579f3d772b74.png)

effect:

![Uploading image.png…]()

**Comment by dayAndnight2018** [comment]
> ** About line**
> Single line's color and Two line's color is not exposed.
> I will expose these property in next version.

okey, hope to be added soon!
