### ISSUE TITLE
[Feature Request] Syntax Highlighting for Codeblocks

### ISSUE THREAD

**Issue by HendrikMennen** [whistyun/Markdown.Avalonia#44]
Hi,
I really like this library.
The only thing I am missing is syntax highlighting for codeblocks. 
It would be really nice to make that possible in the future.

**Comment by whistyun** [comment]
I try to use AvaloniaEdit on [develop-syntaxhigh](https://github.com/whistyun/Markdown.Avalonia/tree/develop-syntaxhigh).

![image](https://user-images.githubusercontent.com/13712028/112722326-325a5780-8f4c-11eb-9c9a-123492f65896.png) ![image](https://user-images.githubusercontent.com/13712028/112722455-02f81a80-8f4d-11eb-9f78-c57b8303e7d2.png)

Markdown.Avalonia will change these syntax highlight colors depending on the theme.
This changing simply change the brightness and saturation of the color depends on the foreground color.

![image](https://user-images.githubusercontent.com/13712028/112722410-ce845e80-8f4c-11eb-81c9-2bb48e620965.png) ![image](https://user-images.githubusercontent.com/13712028/112722499-510d1e00-8f4d-11eb-9dda-8d5a84db87f8.png)

**Comment by whistyun** [comment]
I released v0.10.2 for syntax highlighting.

![img](https://github.com/whistyun/Markdown.Avalonia/wiki/img/code-structure-above.0.10.2.png)
