### ISSUE TITLE
Unicode and emoji support

### ISSUE THREAD

**Issue by hez2010** [whistyun/Markdown.Avalonia#51]
Markdown Avalonia doesn't support Unicode and emojis. 

Text: 💡

Result:

![image](https://user-images.githubusercontent.com/14960345/121118332-3fe56500-c84c-11eb-8b92-bb491bfe0972.png)

Version: 0.10.4

Might related to https://github.com/AvaloniaUI/Avalonia/pull/4893

**Comment by whistyun** [comment]
It is related to AvaloniaUI/Avalonia#4859.
For now, we need to set the FountFamily for workaround.

**Comment by whistyun** [comment]
I released v0.10.6 for fix it.
