### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#53]
If you encountered the same condition when I tap "backspace" key in one kind of input aid software to input something for a TextBox etc, the letter was deleted while a letter in the TextBox also disappeared! Do you know how to fix it?

**Comment by whistyun** [comment]
Sorry, I could not represent same problems.
If you can take screenshots or photos step by step, take them between before and after tapping backspace. And attempt to report it to AvaloniaUI.
I find same probrem in [the Avalonia issue](https://github.com/AvaloniaUI/Avalonia/issues/5272#issuecomment-757573588), but I couldn't find progress to resolve it.

**Comment by dayAndnight2018** [comment]
> Sorry, I could not represent same problems.
> If you can take screenshots or photos step by step, take them between before and after tapping backspace. And attempt to report it to AvaloniaUI.
> I find same probrem in [the Avalonia issue](https://github.com/AvaloniaUI/Avalonia/issues/5272#issuecomment-757573588), but I couldn't find progress to resolve it.

anyway, thank you very much
