### ISSUE TITLE
MarkdownScrollViewer: How to disable vertical scrollbar?

### ISSUE THREAD

**Issue by FoggyFinder** [whistyun/Markdown.Avalonia#57]
That's for case when doc is relatively small and it contains a code-block. Since `TextEditor` has its own `ScrollBar` it leads to displaying 2 `ScrollBars`.

**Comment by whistyun** [comment]
I will disable the vertical scrollbar of `TextEditor`. 
If you can't wait for me, please edit `MarkdownScrollViewer.Styles` to disable `VerticalScrollBarVisibility`.

```xml
<!-- xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia" -->
<!-- xmlns:avedit="https://github.com/avaloniaui/avaloniaedit" -->

<md:MarkdownScrollViewer>
  <md:MarkdownScrollViewer.Styles>
    <Style Selector="avedit|TextEditor">
      <Setter Property="VerticalScrollBarVisibility" Value="Disabled"/>
    </Style>
  </md:MarkdownScrollViewer.Styles>
</md:MarkdownScrollViewer>
```

**Comment by FoggyFinder** [comment]
Thank you. Closing the issue then

**Comment by whistyun** [comment]
v0.10.7 was released to fix this issues.
