### ISSUE TITLE
ContainerBlock can't include a codeblock.

### ISSUE THREAD

**Issue by whistyun** [whistyun/Markdown.Avalonia#61]
for next ver

![image](https://user-images.githubusercontent.com/13712028/141104416-6cb35a7c-5f82-4cf3-aad8-17b549a0b885.png)

**Comment by uxmal** [comment]
Awesome feature! When do you think that next version will be?

**Comment by whistyun** [comment]
> When do you think that next version will be?

may be tomorrow (Friday).

**Comment by whistyun** [comment]
It is fixed. and this feature is supported in [v0.10.8](https://github.com/whistyun/Markdown.Avalonia/releases/tag/v0.10.8).
