### ISSUE TITLE
NullReferenceException in DefaultBitmapLoader.ctor

### ISSUE THREAD

**Issue by exGensImpl** [whistyun/Markdown.Avalonia#63]
For example, if Markdown is created in method called via Avalonia method binding, there is a dynamically compiled method in the stack trace (the method compiled by [MethodToCommandConverter.CreateExecute](https://github.com/AvaloniaUI/Avalonia/blob/e0bae82fdbd254a6bf692b3dca9e3971ba8eeb63/src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs#L100) ). This method have no declaring type, thus we have a NullReferenceException

**Comment by whistyun** [comment]
v0.10.9 was released to fix this issues.
