### ISSUE TITLE
AvaloniaEdit

### ISSUE THREAD

**Issue by nielsbosma** [whistyun/Markdown.Avalonia#65]
Can this dependency be removed? Seems like a bit overkill to include that in a tight markdown library?

**Comment by whistyun** [comment]
Can I release a new package with different name, eg "Markdown.Avalonia.Tight" package, for minimal composition?
I think backwards compatibility is important as much as reducing dependencies.

**Comment by nielsbosma** [comment]
That would be great.

**Comment by nielsbosma** [comment]
Would really appreciate if you could make such a release.

**Comment by whistyun** [comment]
Sorry for the late reply.
I released Markdown.Avalonia.Tight and Markdown.Avalonia.
If you want to remove the dependency of AvaloniaEdit, use [Markdown.Avalonia.Tight](https://www.nuget.org/packages/Markdown.Avalonia.Tight).
If you want to add syntax-highlight later, please switch to Markdown.Avalonia or add Markdown.Avalonia.SyntaxHigh.

**Comment by nielsbosma** [comment]
Thanks a lot! ❤
