### ISSUE TITLE
enhance property for CHyperlink

### ISSUE THREAD

**Issue by whistyun** [whistyun/Markdown.Avalonia#8]
see https://github.com/whistyun/Markdown.Avalonia/issues/4

> If it can be exposed the hyperlink mouse hover and leave after clicked effect could be more appreciate.

**Comment by dayAndnight2018** [comment]
> see #4
> 
> > If it can be exposed the hyperlink mouse hover and leave after clicked effect could be more appreciate.

Thanks a lot for your attentions and patience!

**Comment by whistyun** [comment]
In next version, I support [pseudoclasses](https://avaloniaui.net/docs/styles/styles#pseudoclasses).
It can provide `:hover` `:pointerhover`, `:pressed` for CHyperlink.

`after clicked` (maybe `visited`?) is difficult, Because I don't know how to access hisotry of browser.
It is possible to provide some pseudoclasses meaning clicked while the application is running, However is it usefull?

```xml
<Style Selector="ctxt|CHyperlink">
    <Style.Setters>
        <Setter Property="IsUnderline" Value="true"/>
        <Setter Property="Foreground" Value="Green"/>

        <Setter Property="Padding" Value="2,1" />
        <Setter Property="BorderBrush" Value="Green"/>
        <Setter Property="BorderThickness" Value="2"/>
      </Style.Setters>
    </Style>

    <!--
           it is equls to :pointerover. 
           Because Avalonia-team may change `:pointerover` to `:hover`.
     -->
    <Style Selector="ctxt|CHyperlink:hover">
      <Style.Setters>
        <Setter Property="IsUnderline" Value="true"/>
        <Setter Property="Foreground" Value="Red"/>

        <Setter Property="Padding" Value="5"/>
        <Setter Property="BorderBrush" Value="Red"/>
        <Setter Property="BorderThickness" Value="2"/>
      </Style.Setters>
  </Style>

  <Style Selector="ctxt|CHyperlink:pressed">
      <Style.Setters>
        <Setter Property="IsUnderline" Value="true"/>
        <Setter Property="Foreground" Value="White"/>
        <Setter Property="Background" Value="DarkGreen"/>

        <Setter Property="Padding" Value="2"/>
        <Setter Property="BorderBrush" Value="Gray"/>
        <Setter Property="BorderThickness" Value="2"/>
    </Style.Setters>
</Style>
```

![linkact2](https://user-images.githubusercontent.com/13712028/102006254-f287af80-3d62-11eb-9fa0-3272c2e4128e.gif)
