### ISSUE TITLE
No option to insert image from in memory image

### ISSUE THREAD

**Issue by Shattienator** [whistyun/Markdown.Avalonia#80]
For programmatically generated MD string it is very usefull to feed not only external images from URI or app resources, but from inmemory image - for example I want to add LiveCharts chart as image, but have no find options to feed these kind or images as source.
It is possible to save temp image and feed it to MD as a local image, but it is not a good solution.

**Comment by whistyun** [comment]
In v0.10.12 and v11.0.0-a4, I add the `UseResource` property.
If this property is set to True, `Markdown.Avalonia` looks for images from Resources.
The value, which is set to Resources, should be `Avalonia.Media.Imaging.Bitmap` or `Avalonia.Controls.Control`

If there is no image in Resources, `Markdown.Avalonia` searches [using the same rules as before](https://github.com/whistyun/Markdown.Avalonia/wiki/Image-loading-priority).


**example**  
```xml
<!-- xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia" -->

<Panel>
  <Panel.Resources>
    <Image x:Key="MyImage" Source="/Assets/ResourceImage.png"/>
  </Panel.Resources>
  
  <md:MarkdownScrollViewer UseResource="True" xml:space="preserve">
    <md:MarkdownScrollViewer.Resources>
      <Button x:Key="MyButton" Content="Hello Button"/>
    </md:MarkdownScrollViewer.Resources>
    
    ## Image ##
    
    ![](MyButton)  
    
    ![](MyImage)
    
  </md:MarkdownScrollViewer>
</Panel>
```

![image](https://user-images.githubusercontent.com/13712028/197497009-5cd28ca3-c1f3-4fd9-a64f-f1e0be51db4d.png)
