### ISSUE TITLE
Can you provide compatibility with Avalonia's `11.0.0-preview4` version

### ISSUE THREAD

**Issue by berkansasmaz** [whistyun/Markdown.Avalonia#83]
Hi, we are using this library in an application we are developing. Due to some requirements, we had to use version `11.0.0-preview4` of `Avalonia`. However, this time [some of our features started to not work](https://github.com/AvaloniaUI/Avalonia/issues/9009#issuecomment-1302082720). So we would be very happy if you can provide compatibility with version` 11.0.0-preview4` of `Avalonia`.

**Comment by whistyun** [comment]
I have rebuilt the v11.0.0-a6 package for Avalonia 11.0.0-preview4.
Could you please try it? (I don't have OSX. I tried it on win-x64 and it seems fine)

**Comment by berkansasmaz** [comment]
I tried it works fine. Thanks for the quick action.
