### ISSUE TITLE
I am here again

### ISSUE THREAD

**Issue by dayAndnight2018** [whistyun/Markdown.Avalonia#89]
I am here again just want to ask one question: could we upgrade the ui style ?
first, I want the there has indent before subItems following head tags. just like this:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/44399091/210484176-cb757133-7b18-497e-acac-2fd5238a7ca0.png">
 
that must more beautiful if relative css style is supported.

then, a little bit not polite, do we consider Material Design?

**Comment by dayAndnight2018** [comment]
Besides, could we set the image's width and height ?

**Comment by dayAndnight2018** [comment]
@whistyun

**Comment by whistyun** [comment]
> first, I want the there has indent before subItems following head tags. just like this:

Because of setence element is used in various elements, we should overwrite style various element.

If you use `Fluent` style, the bellow sample helps indent sentence element.

```xml
<!-- xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia" -->
<!-- xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia" -->

<md:MarkdownScrollViewer>
  <md:MarkdownScrollViewer.Styles>
    <Style Selector="ctxt|CTextBlock">
      <Style.Setters>
        <Setter Property="Margin" Value="20,5,0,5" />
      </Style.Setters>
    </Style>
  
    <!-- revert margin for heading -->
    <Style Selector="ctxt|CTextBlock.Heading1, ctxt|CTextBlock.Heading2, ctxt|CTextBlock.Heading3, ctxt|CTextBlock.Heading4">
      <Style.Setters>
        <Setter Property="Margin" Value="0,5" />
      </Style.Setters>
    </Style>
  
    <!-- revert margin for table -->
    <Style Selector="Grid.Table > Border > ctxt|CTextBlock">
      <Style.Setters>
        <Setter Property="Margin" Value="0,5" />
      </Style.Setters>
    </Style>
  
    <!-- revert margin for list -->
    <Style Selector=".List ctxt|CTextBlock">
      <Style.Setters>
        <Setter Property="Margin" Value="0,5" />
      </Style.Setters>
    </Style>
  
    <!-- re-revert margin for list marker -->
    <Style Selector="ctxt|CTextBlock.ListMarker">
      <Style.Setters>
        <Setter Property="Margin" Value="0,5,5,5"/>
      </Style.Setters>
    </Style>
  </md:MarkdownScrollViewer.Styles>
</md:MarkdownScrollViewer>
```

![image](https://user-images.githubusercontent.com/13712028/211568128-ae493d8b-45f5-42c9-a8f9-9b2729c17956.png)

**Comment by whistyun** [comment]
> Do we consider Material Design?

I are not considering adding proprietary styles that apply only within Markdown controls.

To avoid style inconsistencies, Markdown.Avalonia refers to the style theme used in the application (e.g. `Avalonia.Themes.Fluent` or `Avalonia.Themes.Simple`) to determine the style (e.g. SimpleTheme or FluentTheme).

I are considering adding styles for third parties that have their own styles (Aura.UI, FluentAvalonia, Material.Avalonia, etc.), but this approach risks library bloat and we are wondering if we should really adopt it.
