### ISSUE TITLE
Block code does not use mono spaced font (inline code does however)

### ISSUE THREAD

**Issue by g466a** [whistyun/Markdown.Avalonia#90]
Actual Behavior:
- block code using triple backspace shows a block like it should
- highlighting works
- the font is NOT mono spaced

Expected Behavior:
- block code using triple backspace shows a block like it should
- highlighting works
- the font IS mono spaced

Steps to reproduce:
- Start Markdown.AvaloniaDemo (stable or master)
- Scroll down to the block code

What that means for my use case:
- I am building a flash card learning program
- The cards content is md, drawn using Markdown.Avalonia
- One type of card is used to learn guitar tabs and chords, as a type of ascii art
![image](https://user-images.githubusercontent.com/1741421/214023328-7e5f9aa8-821b-40f6-ae8c-1997c49fad90.png)
- Hint: the tabs can get much more complicated and its impossible to read the tabs in that case - in the above example it does not seem to be a big issue

- The tabs and chords are drawn in ascii representation
- The tabs and chords are impossible to use without mono spaced fonts

Workaround:
- use single backspace quote, aka inline code
- problem: looks ugly in this case (background grey very irregular)

**Comment by whistyun** [comment]
v11.0.0-a8 and v0.10.13 fix this issue.

Code blocks with or without syntax highlighting are in monospaced font.

input:  
````md
```c
#include <stdio.h>
int main();
```

```
#include <stdio.h>
int main();
```
````

Output:  
![image](https://user-images.githubusercontent.com/13712028/216367742-11370b57-5966-4042-928e-861a37eec24f.png)
