### ISSUE TITLE
Add support for Avalonia 11.0.0-preview5

### ISSUE THREAD

**Issue by laolarou726** [whistyun/Markdown.Avalonia#94]
Avalonia just released Avalonia 11.0.0-preview5. Any plans to support it?

**Comment by whistyun** [comment]
Markdown.Avalonia.Tight 11.0.0-a9 has been released as a package for preview5.
Note that Markdown.Avalonia.SyntaxHigh has not been released because the dependent library for preview5 has not yet been released.
